py:run "raise Exception('hi')"

imprimir quais entrariam no próximo ciclo

EXCEÇÕES: USAR GENÉRICAS